[package]
name = "mozjpeg-sys-issue-23-example"
version = "0.1.0"
edition = "2018"
authors = ["tyranron <tyranron@gmail.com>"]
publish = false

[dependencies]
anyhow = "1.0"
image = "0.23"
mozjpeg = "0.8"
mozjpeg-sys = "=0.10.13"
#mozjpeg-sys = "=0.10.12"
